### ISSUE TITLE
Why does QI return model within a "model" object rather than at top level ?

### ISSUE THREAD

**Issue by mdutoo** [cgourdin/MartServer#44]
erocci does not.
For instance, MART's:
```
{  
  "model" : [  
    {  
      "id" : "http://schemas.ogf.org/occi/core#",
      "kinds" : [  
        {  
          "term" : "entity",
...
```
vs erocci's:
```
{  
      "kinds" : [  
        {  
          "term" : "entity",
...
```

**Comment by cgourdin** [comment]
I use model because we can import a lot of extensions, to organize the elements by model it is necessary to have a model representation elsewhere this is a big mess if a lot of kinds and mixins are presents in all models and make the interface unreadable. 
In the json rendering (1.2) documentation, there is no global model representation but i found this in page 17/18:
<pre>
<code>
"model": {
      "id": "#model",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resources": {
          "type": "array",
          "items": {
            "$ref": "#definitions/resource"
          }
        },
        "links": {
          "type": "array",
          "items": {
            "$ref": "#definitions/link"
          }
        },
        "mixins": {
          "type": "array",
          "items": {
            "$ref": "#definitions/mixin"
          }
        },
        "kinds": {
          "type": "array",
          "items": {
            "$ref": "#definitions/kind"
          }
        },
        "actions": {
          "type": "array",
          "items": {
            "$ref": "#definitions/action"
          }
        }
      }
    }
  },
</code>
</pre>

**Do i remove the model rendering, and define only kinds, mixins and actions ?**

**Comment by mdutoo** [comment]
Not yet. This is a good reason enough. But then we have to define which operations are available on such models, otherwise of what user are they ?? (and why not returning an array of models rather than again wrapping this array ?)

**Comment by cgourdin** [comment]
I dont understand what you want, a model is for me an extension (as OCCIware define it), model representation is made in array of extensions. how do i must represent this could you give me an example ?

**Comment by mdutoo** [comment]
Let's define later what useful operations this brings to MART and that OCCInterface should bring to its users. Ex.: /-/infrastucture

**Comment by cgourdin** [comment]
The filtering system may works to filter extension representation like you said : /-/infrastructure (or infrastructure/-/), we must discuss about that and implement it in 2017 (this is not much an effort as firstly seen in my code). I keep this open for future developments.
