### ISSUE TITLE
Embed OCCInterface playground

### ISSUE THREAD

**Issue by mdutoo** [cgourdin/MartServer#49]
(not a priority)

OCCInterface is pure html/js (the node.js server is only there to allow it to run in standalone mode) and therefore made to be embedded in OCCI runtimes.
- step 1 : configure the MART server's HTTP server to serve OCCInterface's web assets. You can merely copy them, or checkout them at build time as erocci does...
- step 2 : enrich it with markdown samples that showcase MART's features. It's probably as simple as adding some OCCInterface sample syntax to https://github.com/cgourdin/MartServer/blob/master/doc/userjson.md .

Along with #53 Serve extension doc, this opens up the door to an end-to-end documentation chain.

**Comment by cgourdin** [comment]
Added to my todo list sequence...
