### ISSUE TITLE
action - more lenient & user-friendly (but still OCCI and REST-compliant) syntax

### ISSUE THREAD

**Issue by mdutoo** [cgourdin/MartServer#50]
Make it easier to write requests that are accepted by the MART server, obviously without breaking OCCI, but by accepting some "gray" / not well specified cases.

For instances, to execute an action, this works:

curl -v -X POST -d '{
  "action": "http://schemas.ogf.org/occi/infrastructure/compute/action#start",
  "attributes": {

  }
}' -H 'Content-Type: application/json' -H 'accept: application/json' http://localhost:8080/compute/d99486b7-0632-482d-a184-a9195733ddd3?action=stop

(or at least is should - my own MART says 500 UnsupportedOperationException)

BUT why require the "attributes" field (otherwise "Error while parsing input query") when it is empty ?
why even require the "action" field or the whole JSON body ?

**Comment by mdutoo** [comment]
So let's also add a message to the 500 UnsupportedOperationException : bad server conf, probably missing connector impl. Added corresponding issue in occiware/ecore#181 .

**Comment by cgourdin** [comment]
Issue fixed in 18cc0a0 , if you check it, this must works now. If not please reopen this issue.
