### ISSUE TITLE
wrongly 404 on empty collection

### ISSUE THREAD

**Issue by mdutoo** [cgourdin/MartServer#65]
Should rather return an empty list.
ex. on /compute without having created any yet: 404 { "message" : "resource compute not found", "status" : 404 }

**Comment by cgourdin** [comment]
Ok when querying a collection that has no entities, MartServer must return an empty json if i understand correctly.

**Comment by mdutoo** [comment]
Yes !

**Comment by cgourdin** [comment]
Fixed in commit 62e3347.
